data/urls.py
from django.conf.urls import url, include
from data.views import index, DataFormView, delete_data, list_data, list_city_found, list_city_not_found

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^data_form/(?P<data_id>[0-9a-zA-Z]*)$', DataFormView.as_view(), name="data_form"),
    url(r'^data_list/(?P<city>.+)$', list_data, name="list_data"),
    url(r'^data_delete/(?P<data_id>[0-9a-zA-Z]+)$', delete_data, name="delete_data"),
    url(r'^list_city$', list_city_found, name="list_city"),
    url(r'^list_city_not_found$', list_city_not_found, name="list_city_not_found"),

]


dataproject/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('data.urls', namespace='data'))
]

miner/urls.py
search_page_url = "https://www.tdlr.texas.gov/tools_search/mccs_search.asp"
search_city_form_url = "https://www.tdlr.texas.gov/tools_search/mccs_search_process.asp"
last_page_url = "https://www.tdlr.texas.gov/tools_search/mccs_information_display.asp"

data/models.py
from django.db import models
# Create your models here.


class DataModel(models.Model):
    active_no = models.CharField(max_length=256, db_index=True, verbose_name="Number", null=True)
    city_data_not_found = models.BooleanField(default=False)
    city = models.CharField(max_length=256, db_index=True, verbose_name="City",  null=False)
    name = models.CharField(max_length=256,  default="")
    dba = models.CharField(max_length=256,  default="")
    phone = models.CharField(max_length=256, default="")
    carrier_type = models.CharField(max_length=256, default="")
    active_trucks = models.IntegerField(default=-1)
    mailing_address = models.CharField(max_length=256, default="")
    effective_date = models.CharField(max_length=256, default="")

    #
    checked_manually = models.BooleanField(default=False)
    record_url = models.URLField()  # According to active no


class DifferentDataModel(DataModel):
    """
    When the data scraping app is rerun and then this one is filled up
    But whatever this one provide it will not mess with manually checked Data
    """

data/forms.py
from django import forms

from miner.data.cities_array import cities_choices


class DataFormForm(forms.Form):
    active_no = forms.CharField(required=False, initial="", max_length=256, label="Number")
    city_data_not_found = forms.BooleanField(required=False, initial=False, label="City data not found")
    city = forms.ChoiceField(required=True, choices=cities_choices, label="City")
    name = forms.CharField(required=False, max_length=256, label="Name (Company/Person)")
    dba = forms.CharField(required=False, max_length=256, label="DBA")
    phone = forms.CharField(required=False, max_length=256, label="Phone")
    carrier_type = forms.CharField(required=False, max_length=256, label="Carrier Type")
    active_trucks = forms.IntegerField(required=False, initial=0, label="Active Trucks")
    mailing_address = forms.CharField(required=False, initial="", max_length=256, widget=forms.Textarea(attrs={"rows": 2, "cols": 50}), label="Mailing Address")
    effective_date = forms.CharField(required=False, initial="", max_length=256, label="Effective Date")

    #
    checked_manually = forms.BooleanField(required=False, initial=False, label="Checked Manually?")

    data_id = forms.IntegerField(required=False, widget=forms.HiddenInput)

data/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
# Create your views here.
from django.views import View

from data.forms import DataFormForm
from data.models import DataModel


def index(request):
    return render(request, "index.html")


class DataFormView(View):
    template = "data_form.html"

    def get(self, request, data_id=""):
        city = ""
        if data_id:
            d = DataModel.objects.get(pk=int(data_id))
            city = d.city
            form = DataFormForm(initial={
                "active_no": d.active_no,
                "city_data_not_found" : d.city_data_not_found,
                "city": d.city,
                "name": d.name,
                "dba": d.city,
                "phone": d.phone,
                "carrier_type": d.carrier_type,
                "active_trucks": d.active_trucks,
                "mailing_address": d.mailing_address,
                "effective_date": d.effective_date,
                "checked_manually": d.checked_manually,
                "data_id": d.id
            })
            active_no = d.active_no
        else:
            form = DataFormForm()
            active_no = ""
        return render(request, self.template, context={
            "form": form,
            "city": city,
            "data_id": data_id,
            "active_no": active_no
        })

    def post(self, request, **kwargs):
        form = DataFormForm(request.POST)
        if form.is_valid():
            d = form.cleaned_data
            data_id = d['data_id']
            if data_id == "" or data_id is None:
                # New
                data = DataModel()
            else:
                # Save
                data = DataModel.objects.get(pk=data_id)

            data.active_no = d["active_no"]
            data.city_data_not_found = d["city_data_not_found"]
            data.city = d["city"]
            data.name = d["name"]
            data.dba = d["dba"]
            data.phone = d["phone"]
            data.carrier_type = d["carrier_type"]
            data.active_trucks = d["active_trucks"]
            data.mailing_address = d["mailing_address"]
            data.effective_date = d["effective_date"]
            data.checked_manually = d["checked_manually"]
            data.save()
            data_id = data.id
            messages.info(request, "Data successfully saved")
            return redirect("data:data_form", data_id=data_id)

        else:
            messages.warning(request, "ERROR in the form")
            return render(request, self.template, context={
                "form": form,
                "city": request.POST['city'],
                "data_id": request.POST['data_id'],
                "active_no": request.POST.get("active_no", "")
            })


def list_data(request, city):
    data_by_c = DataModel.objects.all().filter(city__iexact=city)
    # data_by_c.sort()
    return render(request, "data_list.html", context={
        "data_s": data_by_c,
        "city": city
    })


def list_city_found(request):
    a = DataModel.objects.filter(city_data_not_found=False)
    cities = set()
    for d in a:
        cities.add(d.city)

    cities_s = list(cities)
    cities_s.sort()

    return render(request, "list_city.html", context={
        "cities": cities_s
    })


def list_city_not_found(request):
    a = DataModel.objects.filter(city_data_not_found=True)
    cities = set()
    for d in a:
        cities.add(d.city)
    cities_s = list(cities)
    cities_s.sort()
    return render(request, "list_city.html", context={
        "cities": cities_s
    })


def delete_data(request, data_id):
    d = DataModel.objects.get(pk=int(data_id))
    id = d.id
    d.delete()
    messages.info(request, "successfully deleted data id: %s " % id)
    return redirect(request.META['HTTP_REFERER'])

def different_data_list(request):
    pass

def different_data_compare(request):
    pass

def different_data_merge(request):
    pass

data/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}" />
    <script type='text/javascript' src="{% static 'scripts/jquery-3.min.js' %}" > </script>
    <script type='text/javascript' src="{% static 'bootstrap3/js/bootstrap.min.js' %}" > </script>
    
    <title> {% block title %} Data Panel {% endblock title %}</title>
    
    {% block head_plus %}
    
    {% endblock head_plus %}

</head>

<body>


<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Menu</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'data:list_city' %}">Cities</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'data:list_city_not_found' %}">Cities Not Found</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li><a href="{% url 'data:data_form' ''%}">New Data</a></li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>





<div id="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            {% block flash_messages %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.level_tag == 'error' %}
                            <div class="alert alert-danger alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                {{message.message}}
                            </div>
                        {% elif message.level_tag == 'debug' %}
                            <div class="alert alert-warning django-debug alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                {{message.message}}
                            </div>
                        {% else %}
                            <div class="alert alert-{{message.level_tag}} alert-dismissable">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                {{message.message}}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endblock flash_messages %}

        </div>

    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            {% block content %}

            {% endblock %}
        </div>
    </div>

</div>

    {% block body_end_plus %}
        
    {% endblock body_end_plus %}
</body>
</html>


data/templates/data_form.html
{% extends "./base.html" %}
{% load bootstrap %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if data_id and city %}
                <a href="{% url 'data:list_data' city=city %}#data-id-{{ data_id }}"> Go back to the row </a>
            {% endif %}

            <br />
            <form method="post" action="{% url 'data:data_form' data_id=''%}" class="" id="data_form">
                {% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" class="btn btn-default" id="submit_button">Save</button>
            </form>
            <br/>
            <br/>
            Go to the city: {% if city %} <a href="{% url 'data:list_data' city=city %}">{{ city }}</a> {% endif %}
            <br/>
            <br/>
        </div>


{#        <div class="col-md-6" style="height: 500px; overflow-x: scroll">#}
{#            {% if active_no %}#}
{#                <iframe href="https://www.tdlr.texas.gov/tools_search/mccs_display.asp?mcrnumber={{ active_no }}">#}
{##}
{#                </iframe>#}
{#            {% endif %}#}
{#        </div>#}
    </div>


{% endblock %}

data/templates/data_list.html
{% extends "./base.html" %}
{% load bootstrap %}

{% block content %}
    City: &nbsp; {{ city }}
    <hr>
    <table id="data-table" class="table table-bordered table-responsive">
        <tr>
            <td>Edit</td>
            <td>Delete</td>
            <th> id </th> <th>City </th> <th> Not Found? </th> <th> Name </th> <th> DBA </th> <th> phone </th> <th>carrier type</th>
            <th>active trucks</th> <th> mailing address </th> <th> effective date </th> <th>Checked manually?</th> <th> Record Url </th>
        </tr>
    {% for d in data_s %}
        <tr id="data-id-{{d.id}}">
            <td> <a href="{% url 'data:data_form' data_id=d.id %}"> edit </a> </td>  <td> <a href="{% url 'data:delete_data' data_id=d.id %}">delete</a> </td>
            <td> {{d.id}} </td> <td> {{d.city}} </td>

            <td> {%  if d.city_data_not_found %} <span style="background-color: red">X</span> {% endif %}</td>

            <td> {{d.name}} </td> <td> {{s.dba}} </td> <td>{{ d.phone }}</td>
            <td>{{ d.carrier_type }}</td> <td> {{ d.active_trucks }} </td>
            <td> {{ d.mailing_address|linebreaks }} </td> <td>{{ d.effective_date }}</td>
            <td>{{ d.checked_manually|yesno:"Yes,No,-" }}</td>
            <td>{% if not d.city_data_not_found %} <a href="{{ d.record_url }}">Record Link</a> {% endif %}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

{% block body_end_plus %}
    <script>
        var all_data = {{ data_s }};

{#        $(document).ready(function () {#}
{#                var data_table = $("#data-table");#}
{##}
{#                all_data.forEach(function(d, idx, arr){#}
{#                    var str =#}
{#                        '<tr id="data-id-"' + d.id + '">' +\#}
{#                        '<td>' + d.id + '</td> <td>' {{tag.slug}} </td> <td> {{tag.title}} </td> <td> {{tag.language_code}} </td> <td> {{tag.description|truncatechars:100}} </td> <td> <a href="{% url 'sabuj_me_webapp:new_or_edit_tag' tag_id=tag.id %}"> edit </a> </td>  <td> <a href="{% url 'sabuj_me_webapp:delete_tag' tag.id %}">delete</a> </td>#}
{#                    </tr>';#}
{#                });#}
{##}
{##}
{#            }#}
{#        );#}

        function onClick_data_edit(evt){

        }
    </script>
{% endblock body_end_plus %}

data/templates/different_data_list.html
{% extends "./base.html" %}
{% load bootstrap %}

{% block content %}




    <br/>
    <br/>
    Go to the city: {{ city }} {% if city %} <a href="{% url 'data:list_data' city=city %}">{{ city }}</a> {% endif %}
    <br/>
    <br/>

{% endblock %}

data/templates/index.html
{% extends './base.html' %}

data/templates/list_city.html
{% extends "./base.html" %}
{% load bootstrap %}

{% block content %}
    <ol>
        {% for city in cities %}
            <li>
                <a href="{% url 'data:list_data' city=city %}">{{ city }}</a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}